### ISSUE TITLE
Ontology not accessable

### ISSUE THREAD

**Issue by jeffchy** [lemaoliu/fet-data#1]
Hello, interesting work!
I want to access the ontology at link https://ai.tencent.com/ailab/nlp/texsmart/download/texsmart-ont-0.3.5.tar.gz, but I find I download an empty file.
Could you please provide the ontology？

**Comment by lemaoliu** [comment]
Hi Jeff, thanks for your feedback. The data is attached.

It seems that there is some issue with the url, because I can download it.
I will try to fix it soon.

Best,

Lemao

Jeff Chiang ***@***.***> 于2022年1月20日周四 19:22写道：

**Comment by lemaoliu** [comment]
Hi Jeff, thanks for your feedback. The texsmart-ont-0.3.5.tar.gz is located in the git repo now.

**Comment by jeffchy** [comment]
thanks~

**Comment by jeffchy** [comment]
The ontology file is sized 188 Bytes, and it appears to be an empty folder?

**Comment by lemaoliu** [comment]
I am very sorry that I made a mistake. Now it is fixed.

Jeff Chiang ***@***.***> 于2022年1月20日周四 21:38写道：

**Comment by lemaoliu** [comment]
The file is updated last night. Please try it again. Thanks.



发自我的iPhone


------------------ Original ------------------
From: Jeff Chiang ***@***.***&gt;
Date: Thu,Jan 20,2022 9:38 PM
To: lemaoliu/fet-data ***@***.***&gt;
Cc: Lemao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [lemaoliu/fet-data] Ontology not accessable (Issue #1)





 
The ontology file is sized 188 Bytes, and it appears to be an empty folder?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
